In [1]:
import glob

import pandas as pd

In [2]:
# Aggregation function list
agg_func_list = ["mean", "median"]

In [3]:
agg_func = "mean"
files = glob.glob(f"experiments/agg_func_{agg_func}*.csv")
df = pd.concat([pd.read_csv(file) for file in files]).reset_index(drop=True)
display(df.sort_values("r2_test_reduced", ascending=False))
grouped = df.groupby(["test_size", "n_features_reduced"])["r2_test_reduced_gain"].median().reset_index()
top_test_size = grouped.sort_values("r2_test_reduced_gain", ascending=False).head(1)["test_size"].values[0]
top_n_features_reduced = grouped.sort_values("r2_test_reduced_gain", ascending=False).head(1)["n_features_reduced"].values[0]
df[(df["test_size"] == top_test_size) & (df["n_features_reduced"] == top_n_features_reduced)]

,iteration,agg_func,test_size,n_features,r2_train,r2_test,n_features_reduced,r2_train_reduced,r2_test_reduced,r2_test_reduced_gain
67,8,mean,0.3,82,0.904591,0.469334,10,0.869362,0.653948,0.184615
125,6,mean,0.5,82,0.954993,0.561835,10,0.962752,0.633442,0.071607
84,5,mean,0.3,82,0.945298,0.546898,20,0.889452,0.626662,0.079764
77,8,mean,0.3,82,0.922012,0.567824,15,0.893055,0.621208,0.053384
61,2,mean,0.3,82,0.937746,0.577267,10,0.875979,0.619535,0.042268
...,...,...,...,...,...,...,...,...,...,...
12,3,mean,0.1,82,0.949885,0.411506,15,0.956968,0.364880,-0.046626
36,7,mean,0.2,82,0.925166,0.402140,10,0.910557,0.361096,-0.041044
33,4,mean,0.2,82,0.952240,0.470623,10,0.959910,0.352427,-0.118196
39,10,mean,0.2,82,0.941633,0.461018,10,0.883008,0.332395,-0.128623
23,4,mean,0.1,82,0.922306,0.548229,20,0.911308,0.302881,-0.245348

,iteration,agg_func,test_size,n_features,r2_train,r2_test,n_features_reduced,r2_train_reduced,r2_test_reduced,r2_test_reduced_gain
80,1,mean,0.3,82,0.931301,0.554484,20,0.909900,0.596557,0.042073
81,2,mean,0.3,82,0.943138,0.570068,20,0.854554,0.571027,0.000959
82,3,mean,0.3,82,0.841852,0.462037,20,0.867042,0.557527,0.095490
83,4,mean,0.3,82,0.936292,0.529855,20,0.884820,0.575472,0.045617
84,5,mean,0.3,82,0.945298,0.546898,20,0.889452,0.626662,0.079764
85,6,mean,0.3,82,0.929881,0.590694,20,0.882705,0.613869,0.023174
86,7,mean,0.3,82,0.949156,0.528328,20,0.898892,0.613288,0.084960
87,8,mean,0.3,82,0.950810,0.579780,20,0.882115,0.568314,-0.011466
88,9,mean,0.3,82,0.929364,0.550958,20,0.868903,0.576524,0.025566
89,10,mean,0.3,82,0.937035,0.562781,20,0.906229,0.612880,0.050098

In [4]:
agg_func = "median"
files = glob.glob(f"experiments/agg_func_{agg_func}*.csv")
df = pd.concat([pd.read_csv(file) for file in files]).reset_index(drop=True)
display(df.sort_values("r2_test_reduced", ascending=False))
grouped = df.groupby(["test_size", "n_features_reduced"])["r2_test_reduced_gain"].median().reset_index()
top_test_size = grouped.sort_values("r2_test_reduced_gain", ascending=False).head(1)["test_size"].values[0]
top_n_features_reduced = grouped.sort_values("r2_test_reduced_gain", ascending=False).head(1)["n_features_reduced"].values[0]
df[(df["test_size"] == top_test_size) & (df["n_features_reduced"] == top_n_features_reduced)]

,iteration,agg_func,test_size,n_features,r2_train,r2_test,n_features_reduced,r2_train_reduced,r2_test_reduced,r2_test_reduced_gain
82,3,median,0.3,82,0.866975,0.548478,20,0.924794,0.654489,0.106011
73,4,median,0.3,82,0.936226,0.592813,15,0.934386,0.646291,0.053478
70,1,median,0.3,82,0.932017,0.560402,15,0.957972,0.640003,0.079601
63,4,median,0.3,82,0.951920,0.621120,10,0.874670,0.634188,0.013068
66,7,median,0.3,82,0.845361,0.548216,10,0.888548,0.627169,0.078953
...,...,...,...,...,...,...,...,...,...,...
19,10,median,0.1,82,0.915311,0.479318,15,0.956688,0.384864,-0.094455
36,7,median,0.2,82,0.941007,0.503653,10,0.869542,0.368579,-0.135074
30,1,median,0.2,82,0.842899,0.529884,10,0.913636,0.366162,-0.163722
9,10,median,0.1,82,0.837507,0.474518,10,0.917804,0.347435,-0.127084
8,9,median,0.1,82,0.878094,0.456907,10,0.902476,0.328013,-0.128893

,iteration,agg_func,test_size,n_features,r2_train,r2_test,n_features_reduced,r2_train_reduced,r2_test_reduced,r2_test_reduced_gain
110,1,median,0.4,82,0.861978,0.426365,20,0.932570,0.539244,0.112879
111,2,median,0.4,82,0.946448,0.527418,20,0.888985,0.576741,0.049323
112,3,median,0.4,82,0.954392,0.526512,20,0.924663,0.568170,0.041659
113,4,median,0.4,82,0.948135,0.545161,20,0.969164,0.588583,0.043422
114,5,median,0.4,82,0.947620,0.547241,20,0.964600,0.567789,0.020548
115,6,median,0.4,82,0.933589,0.517077,20,0.968155,0.553077,0.036000
116,7,median,0.4,82,0.938454,0.521398,20,0.925446,0.530288,0.008891
117,8,median,0.4,82,0.956262,0.547980,20,0.948526,0.545578,-0.002402
118,9,median,0.4,82,0.937643,0.514501,20,0.919051,0.600789,0.086289
119,10,median,0.4,82,0.948649,0.507906,20,0.906182,0.565321,0.057414